language: python
sudo: required
dist: xenial
python:
  - 3.7

before_install:
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends libxml2-dev libxslt1-dev libre2-dev pkg-config

install:
  - travis_retry pip install --upgrade pip setuptools
  - travis_retry pip install --process-dependency-links --no-binary --upgrade .

script:
  - ./tests/offline-tests
  - ./tests/online-tests
